name: build ios

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - run: brew install tree
    - name: Download Pre Compiled Dependencies
      run: cd shell && ./download-pre.sh ios 0.10.1-230831144049-ijk
    - run: pod lib lint --allow-warnings --platforms=ios
